name: release

on:
  push:
    tags:
      - v*

permissions:
  contents: write
  pull-requests: write

jobs:
 release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.4
        with:
          fetch-depth: 0

      - uses: actions/setup-go@v5.0.1
        with:
          go-version: "1.22"

      - name: Run goreleaser
        uses: goreleaser/goreleaser-action@v5.1.0
        with:
          version: "1.26.1"
          args: release --clean --config .goreleaser.yaml
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
